prm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'Rev121'
    right_wheel: 'Rev120'
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  camera_pan_controller:
    type: "effort_controllers/JointPositionController"
    joint: "Pan_joint"
    pid: {p: 1.0, i: 1.0, d: 0.0}

  camera_tilt_controller:
    type: "effort_controllers/JointPositionController"
    joint: "Tilt_joint"
    pid: {p: 1.0, i: 1.0, d: 0.0}
